<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('languages')->insert([
            ['language_name' => 'HTML'],
            ['language_name' => 'CSS'],
            ['language_name' => 'Python'],
            ['language_name' => 'PHP'],
            ['language_name' => 'JavaScript'],
            ['language_name' => 'Ruby'],
            ['language_name' => 'Java'],
            ['language_name' => 'SQL'],
            ['language_name' => 'C'],
            ['language_name' => 'C#'],
            ['language_name' => 'C++'],
            ['language_name' => 'Swift'],
            ['language_name' => 'Kotlin'],
            ['language_name' => 'Dart'],
            ['language_name' => 'Rust'],
            ['language_name' => 'Go'],
            ['language_name' => 'TypeScript'],
            ['language_name' => 'Rust'],
            ['language_name' => 'Scala'],
            ['language_name' => 'Perl'],
            ['language_name' => 'R'],
            ['language_name' => 'Objective-C'],
            ['language_name' => 'React'],
            ['language_name' => 'Next.js'],
            ['language_name' => 'Vue.js'],
            ['language_name' => 'Angular'],
            ['language_name' => 'Node.js'],
            ['language_name' => 'Laravel'],
            ['language_name' => 'Ruby on Rails'],
            ['language_name' => 'Spring'],
            ['language_name' => 'Django'],
            ['language_name' => 'Flask'],
            ['language_name' => 'Express'],
            ['language_name' => 'jQuery'],
            ['language_name' => 'Bootstrap'],
            ['language_name' => 'Tailwind CSS'],
            ['language_name' => 'Sass'],
            ['language_name' => 'Less'],
            ['language_name' => 'Stylus'],
            ['language_name' => 'PostCSS'],
            ['language_name' => 'Redux'],
            ['language_name' => 'Vuex'],
            ['language_name' => 'MobX'],
            ['language_name' => 'GraphQL'],
            ['language_name' => 'Apollo Client'],
            ['language_name' => 'REST API'],
            ['language_name' => 'WebSocket'],
            ['language_name' => 'gRPC'],
            ['language_name' => 'Docker'],
            ['language_name' => 'Kubernetes'],
            ['language_name' => 'Vagrant'],
            ['language_name' => 'Ansible'],
            ['language_name' => 'Chef'],
            ['language_name' => 'Puppet'],
            ['language_name' => 'Terraform'],
            ['language_name' => 'AWS'],
            ['language_name' => 'GCP'],
            ['language_name' => 'Azure'],
            ['language_name' => 'Firebase'],
            ['language_name' => 'Netlify'],
            ['language_name' => 'Vercel'],
            ['language_name' => 'Heroku'],
            ['language_name' => 'GitHub'],
            ['language_name' => 'GitLab'],
            ['language_name' => 'Bitbucket'],
            ['language_name' => 'Jenkins'],
            ['language_name' => 'CircleCI'],
            ['language_name' => 'Travis CI'],
            ['language_name' => 'GitHub Actions'],
        ]);
    }
}
